const mafiaMoonQuotes = [
    "The moon whispers secrets only the mafia dares to understand.",
    "Under the moon's cold gaze, deals are made and promises broken.",
    "Like the moon, the mafia’s power is both a light and a shadow.",
    "The mafia moves with the moon, silent yet impossible to ignore.",
    "Beneath the silver moon, loyalty is tested, and betrayals unfold.",
    "The moon shines brightest on the roads less traveled by the mafia.",
    "Both the moon and the mafia illuminate the darkness in their own ways.",
    "The moon is a silent witness to the mafia’s unspoken codes.",
    "Like the moon, the mafia rises with the night, unseen by the day.",
    "The mafia's schemes are as constant as the phases of the moon.",
    "In the moonlight, the mafia’s sins shimmer like uncut diamonds.",
    "The mafia and the moon thrive in the quiet solitude of midnight.",
    "Every full moon sees the mafia’s plans come to fruition.",
    "Under the moon’s glow, the mafia turns chaos into order.",
    "The moon keeps its distance, much like a mafia boss.",
    "The mafia operates in shadows, but the moonlight always finds them.",
    "Both the moon and the mafia carry a quiet, commanding presence.",
    "The mafia’s power waxes and wanes, much like the cycles of the moon.",
    "When the moon is high, the mafia’s empire feels untouchable.",
    "The moonlight reflects the duality of the mafia: beauty and danger.",
    "Beneath the moon, vengeance is a vow the mafia always keeps.",
    "The moon illuminates the path for the mafia’s midnight crusades.",
    "In the mafia’s world, the moon is both a guide and a judge.",
    "The moon's glow outlines the edges of the mafia’s dark kingdom.",
    "Every mafia empire is born under the watchful eye of the moon.",
    "The moon witnesses the rise and fall of every mafia dynasty.",
    "The mafia claims the moonlit streets as their dominion.",
    "The moon sees all but says nothing, much like a mafia consigliere.",
    "Under the moon, every mafia secret is just another shade of gray.",
    "The moon’s cycles remind the mafia of the impermanence of power.",
    "The moon casts its light, but the mafia controls the shadows.",
    "In the mafia’s world, the moon is both a poet and a prophet.",
    "The moonlight reveals what the mafia works so hard to conceal.",
    "The moon watches over the city as silently as a mafia don, its pale glow concealing secrets in the shadows.",
    "The mafia rules the night as the moon rules the tides.",
    "The moon shines brightest where the mafia’s influence is darkest.",
    "Under the moon’s gaze, the mafia’s honor is both sacred and fleeting.",
    "The mafia’s secrets drift like whispers in the moonlit air.",
    "The moon and the mafia share an eternal dance of light and dark.",
    "The moon reveals the mafia’s elegance, even in their brutality.",
    "Knowledge is power, but only when it's applied effectively.",
  "An investment in knowledge pays the best interest – Benjamin Franklin.",
  "Knowledge empowers us to shape the world, while ignorance leaves us at its mercy.",
  "Power derived from knowledge grows as it is shared, not hoarded.",
  "The wise wield knowledge like a sword, cutting through confusion and fear.",
  "True power lies in understanding, and understanding comes from knowledge.",
  "Knowledge unlocks doors to opportunities that remain closed to the uninformed.",
  "In the digital age, knowledge is not just power but a survival tool.",
  "Knowledge without action is potential, but action transforms it into power.",
  "To seek knowledge is to seek the tools to change your life and the world."
  ];
export default mafiaMoonQuotes  